<?php
/**
 * @file
 * Code for the Reload Jira Update feature.
 */

include_once 'reload_jira_update.features.inc';

/**
 * Implements hook_jira_rest_rules_issuedata_alter().
 *
 * Add project status, project name, and site-name as labels.
 */
function reload_jira_update_jira_rest_rules_issuedata_alter(array &$issuedata, array &$settings, &$operation) {
  if ($operation == 'create') {
    $labels = array();

    if (!empty($settings['state']->variables['status_label'])) {
      $labels[] = drupal_clean_css_identifier($settings['state']->variables['status_label']);
    }

    if (!empty($settings['state']->variables['project_name'])) {
      $labels[] = $settings['state']->variables['project_name'];
    }

    if ($site_name = variable_get('site_name', FALSE)) {
      $labels[] = $site_name;
      $issuedata['fields']['customfield_12300'] = $site_name;
    }

    $issuedata['fields']['labels'] = $labels;
  }
}
